GET = http://localhost:5000/api/services/643c4e011076b1e4b293d2e2

###
DELETE GET = http://localhost:5000/api/services/643c4e011076b1e4b293d2e2
###

PUT = "http://localhost:5000/api/services/643c4e011076b1e4b293d2e2"
Content-Type: application/json
{
    "name": "somebody service 2",
    "description": "somebody service description",
    "price": 1800,
    "image":"/img/cacto.png"
}